// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoev5DKHNakXu3PoMNNaFp7sxLvKoc8QY',
    appId: '1:1015455731858:web:b0f9c5a95249802660964b',
    messagingSenderId: '1015455731858',
    projectId: 'praner-blog',
    authDomain: 'praner-blog.firebaseapp.com',
    storageBucket: 'praner-blog.appspot.com',
    measurementId: 'G-QET8S4E15V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7q1I8Ow5ZTdnYAZdIuSQVIuSWEgWhbR4',
    appId: '1:1015455731858:android:4aa83a756ff5ce0560964b',
    messagingSenderId: '1015455731858',
    projectId: 'praner-blog',
    storageBucket: 'praner-blog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFSJx-NgOphnKtYMGMrI8tex9bgI2hJpc',
    appId: '1:1015455731858:ios:3bd51f94570f0ddf60964b',
    messagingSenderId: '1015455731858',
    projectId: 'praner-blog',
    storageBucket: 'praner-blog.appspot.com',
    iosBundleId: 'com.example.pranerBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFSJx-NgOphnKtYMGMrI8tex9bgI2hJpc',
    appId: '1:1015455731858:ios:3bd51f94570f0ddf60964b',
    messagingSenderId: '1015455731858',
    projectId: 'praner-blog',
    storageBucket: 'praner-blog.appspot.com',
    iosBundleId: 'com.example.pranerBlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoev5DKHNakXu3PoMNNaFp7sxLvKoc8QY',
    appId: '1:1015455731858:web:edf250648297009560964b',
    messagingSenderId: '1015455731858',
    projectId: 'praner-blog',
    authDomain: 'praner-blog.firebaseapp.com',
    storageBucket: 'praner-blog.appspot.com',
    measurementId: 'G-FM0G9XRV11',
  );
}
